/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2012
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
package com.ericsson.oss.services.security.model.npam.job;

import com.ericsson.oss.itpf.modeling.annotation.EModel;
import com.ericsson.oss.itpf.modeling.annotation.edt.EdtDefinition;
import com.ericsson.oss.itpf.modeling.annotation.edt.EdtMember;
import com.ericsson.oss.services.security.model.npam.NPamModelsConstants;

@EModel(namespace = NPamModelsConstants.NAME_SPACE, name = "JobType", version = NPamModelsConstants.VERSION, description = "Type of the  Job")
@EdtDefinition
public enum JobType {

    @EdtMember(value = 1, description = "Rotate NetworkElementAccount credentials")
    ROTATE_NE_ACCOUNT_CREDENTIALS,

    @EdtMember(value = 2, description = "Rotate NetworkElementAccount credentials (autogenerated)")
    ROTATE_NE_ACCOUNT_CREDENTIALS_AUTOGENERATED,

    @EdtMember(value = 3, description = "Rotate NetworkElementAccount credentials (from file)")
    ROTATE_NE_ACCOUNT_CREDENTIALS_FROM_FILE,

    @EdtMember(value = 4, description = "Create NetworkElementAccount")
    CREATE_NE_ACCOUNT,

    @EdtMember(value = 5, description = "Detach NetworkElementAccount")
    DETACH_NE_ACCOUNT,

    @EdtMember(value = 6, description = "Check and Update NetworkElementAccount configuration")
    CHECK_AND_UPDATE_NE_ACCOUNT_CONFIGURATION
}
